// <auto-generated />
using GeekShopping.ProductApi.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductApi.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20250108004106_SeadProductDataTable")]
    partial class SeadProductDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GeekShopping.ProductApi.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Category 2",
                            Description = "Description 2",
                            ImageURL = "https://www.heidisql.com/download.php",
                            Name = "Name 2",
                            Price = 70.8m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Category 5",
                            Description = "Description 5",
                            ImageURL = "https://www.heidisql.com/download.php",
                            Name = "Name 5",
                            Price = 120.1m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Category 6",
                            Description = "Description 6",
                            ImageURL = "https://www.heidisql.com/download.php",
                            Name = "Name 6",
                            Price = 60.88m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Category 7",
                            Description = "Description 7",
                            ImageURL = "https://www.heidisql.com/download.php",
                            Name = "Name 7",
                            Price = 170.8m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
